import { Module, Algorithm, GlossaryTerm } from "@/types"

export const modules: Module[] = [
  {
    id: "m1-fundamental",
    number: 1,
    title: "Fundamental ML",
    description: "Pelajari apa itu Machine Learning, bedanya dengan pemrograman tradisional, dan mengapa ML relevan saat ini.",
    icon: "brain",
    totalDuration: 45,
    chapters: [
      { id: "m1-apa-itu-ml", title: "Apa Itu Machine Learning?", duration: 10 },
      { id: "m1-tradisional-vs-ml", title: "Pemrograman Tradisional vs ML", duration: 8 },
      { id: "m1-kenapa-ml", title: "Mengapa ML Relevan Saat Ini?", duration: 7 },
      { id: "m1-istilah-dasar", title: "Istilah Dasar dalam ML", duration: 12 },
      { id: "m1-kuis", title: "Kuis Fundamental", duration: 8 },
    ],
  },
  {
    id: "m2-jenis-ml",
    number: 2,
    title: "Tiga Jenis ML",
    description: "Pahami perbedaan Supervised, Unsupervised, dan Reinforcement Learning beserta contoh penerapannya.",
    icon: "layers",
    totalDuration: 50,
    chapters: [
      { id: "m2-supervised", title: "Supervised Learning", duration: 15 },
      { id: "m2-unsupervised", title: "Unsupervised Learning", duration: 12 },
      { id: "m2-reinforcement", title: "Reinforcement Learning", duration: 10 },
      { id: "m2-perbandingan", title: "Perbandingan & Contoh Penerapan", duration: 8 },
      { id: "m2-kuis", title: "Kuis Jenis ML", duration: 5 },
    ],
  },
  {
    id: "m3-supervised",
    number: 3,
    title: "Konsep Dasar Supervised Learning",
    description: "Klasifikasi vs Regresi, anatomi dataset, training/testing split, overfitting & underfitting.",
    icon: "target",
    totalDuration: 55,
    chapters: [
      { id: "m3-klasifikasi-regresi", title: "Klasifikasi vs Regresi", duration: 12 },
      { id: "m3-anatomi-dataset", title: "Anatomi Dataset", duration: 8 },
      { id: "m3-train-test-split", title: "Training/Testing Split", duration: 10 },
      { id: "m3-overfitting", title: "Overfitting & Underfitting", duration: 15 },
      { id: "m3-feature-importance", title: "Feature Importance", duration: 5 },
      { id: "m3-kuis", title: "Kuis Supervised Learning", duration: 5 },
    ],
  },
  {
    id: "m4-ensiklopedia",
    number: 4,
    title: "Ensiklopedia Algoritma",
    description: "Jelajahi 8 algoritma ML utama: Linear Regression, Decision Tree, Random Forest, SVM, KNN, Gradient Boosting, Neural Network, K-Means.",
    icon: "grid",
    totalDuration: 120,
    chapters: [
      { id: "m4-linear-regression", title: "Linear & Logistic Regression", duration: 15 },
      { id: "m4-decision-tree", title: "Decision Tree", duration: 15 },
      { id: "m4-random-forest", title: "Random Forest", duration: 15 },
      { id: "m4-svm", title: "Support Vector Machine (SVM)", duration: 15 },
      { id: "m4-knn", title: "K-Nearest Neighbors (KNN)", duration: 15 },
      { id: "m4-gradient-boosting", title: "Gradient Boosting", duration: 15 },
      { id: "m4-neural-network", title: "Neural Network", duration: 15 },
      { id: "m4-k-means", title: "K-Means Clustering", duration: 15 },
    ],
  },
  {
    id: "m5-evaluasi",
    number: 5,
    title: "Evaluasi Model",
    description: "Pelajari metrik evaluasi: akurasi, precision, recall, F1, RMSE, MAE, dan cross-validation.",
    icon: "bar-chart",
    totalDuration: 50,
    chapters: [
      { id: "m5-metrik-klasifikasi", title: "Metrik Klasifikasi", duration: 12 },
      { id: "m5-metrik-regresi", title: "Metrik Regresi", duration: 10 },
      { id: "m5-confusion-matrix", title: "Confusion Matrix", duration: 10 },
      { id: "m5-cross-validation", title: "Cross-Validation", duration: 10 },
      { id: "m5-kuis", title: "Kuis Evaluasi Model", duration: 8 },
    ],
  },
  {
    id: "m6-studi-kasus",
    number: 6,
    title: "Studi Kasus Terapan",
    description: "Studi kasus IoT pertanian presisi: monitoring tanah untuk budidaya kopi dengan Random Forest.",
    icon: "leaf",
    totalDuration: 60,
    chapters: [
      { id: "m6-iot-intro", title: "Sistem IoT untuk Pertanian", duration: 10 },
      { id: "m6-sensor-data", title: "Data Sensor & Preprocessing", duration: 12 },
      { id: "m6-model-random-forest", title: "Membangun Model Random Forest", duration: 15 },
      { id: "m6-dashboard", title: "Dashboard Monitoring", duration: 10 },
      { id: "m6-kuis", title: "Kuis Studi Kasus", duration: 8 },
    ],
  },
]

export const algorithms: Algorithm[] = [
  {
    id: "linear-regression",
    number: 1,
    name: "Linear & Logistic Regression",
    nameId: "Linear & Logistic Regression",
    category: "supervised",
    taskType: "Regresi / Klasifikasi",
    complexity: "O(n)",
    minData: "> 100 sampel",
    summary: "Linear Regression memodelkan hubungan antara variabel independen dan dependen sebagai garis lurus. Logistic Regression menggunakan fungsi sigmoid untuk mengubah output linear menjadi probabilitas klasifikasi biner.",
    analogy: "Seperti menarik garis lurus di antara titik-titik di papan dart — garis terbaik adalah yang jarak rata-ratanya ke semua titik paling kecil.",
    icon: "trending-up",
    pros: [
      "Sederhana dan mudah diinterpretasi",
      "Cepat dilatih dan dijalankan",
      "Memberikan insight tentang hubungan antar fitur",
      "Foundation untuk algoritma yang lebih kompleks",
    ],
    cons: [
      "Mengasumsikan hubungan linear antar fitur",
      "Sensitif terhadap outlier",
      "Performa buruk pada data non-linear tanpa transformasi",
      "Mudah overfit dengan banyak fitur",
    ],
    applications: [
      "Prediksi harga rumah berdasarkan fitur (luas, lokasi, kamar)",
      "Prediksi probabilitas email spam (Logistic Regression)",
      "Analisis dampak suhu terhadap hasil panen kopi",
      "Prediksi churn pelanggan",
    ],
  },
  {
    id: "decision-tree",
    number: 2,
    name: "Decision Tree",
    nameId: "Decision Tree",
    category: "supervised",
    taskType: "Klasifikasi & Regresi",
    complexity: "O(n·m·log n)",
    minData: "> 50 sampel",
    summary: "Decision Tree bekerja seperti diagram alir: setiap simpul internal adalah pertanyaan tentang fitur, setiap cabang adalah jawaban, dan setiap daun adalah keputusan akhir.",
    analogy: "Seperti permainan '20 Pertanyaan' — setiap pertanyaan mempersempit kemungkinan hingga tersisa satu jawaban.",
    icon: "git-branch",
    pros: [
      "Mudah divisualisasikan dan diinterpretasi",
      "Tidak memerlukan scaling data",
      "Menangani data kategorikal dan numerik",
      "Feature importance bawaan",
    ],
    cons: [
      "Mudah overfit jika pohon terlalu dalam",
      "Sensitif terhadap perubahan kecil dalam data",
      "Bisa menjadi sangat kompleks dengan banyak cabang",
      "Variance tinggi (model berbeda pada dataset berbeda)",
    ],
    applications: [
      "Diagnosis penyakit berdasarkan gejala",
      "Klasifikasi kualitas tanah untuk pertanian",
      "Sistem rekomendasi sederhana",
      "Analisis risiko kredit",
    ],
  },
  {
    id: "random-forest",
    number: 3,
    name: "Random Forest",
    nameId: "Random Forest",
    category: "supervised",
    taskType: "Klasifikasi & Regresi",
    complexity: "O(n log n)",
    minData: "> 200 sampel",
    summary: "Random Forest menggabungkan banyak Decision Tree yang dilatih pada subset data acak, lalu 'memilih' hasil terbanyak (klasifikasi) atau rata-rata (regresi) dari seluruh pohon.",
    analogy: "Seperti bertanya ke 100 pakar — masing-masing melihat data dari sudut pandang berbeda, lalu kita ambil suara terbanyak. Hasilnya lebih akurat daripada bertanya ke satu orang.",
    icon: "trees",
    pros: [
      "Akurasi tinggi untuk berbagai jenis data",
      "Mengatasi overfitting lebih baik dari Decision Tree tunggal",
      "Menangani missing data dengan baik",
      "Feature importance yang reliable",
    ],
    cons: [
      "Lebih lambat dari Decision Tree tunggal",
      "Kurang interpretabel (black box dibanding Decision Tree)",
      "Membutuhkan lebih banyak memori",
      "Bisa overfit pada data noisy",
    ],
    applications: [
      "Klasifikasi kualitas kopi berdasarkan sensor tanah (Studi Kasus IoT)",
      "Prediksi penyakit tanaman",
      "Deteksi fraud transaksi",
      "Klasifikasi jenis tumor",
    ],
  },
  {
    id: "svm",
    number: 4,
    name: "SVM (Support Vector Machine)",
    nameId: "SVM (Support Vector Machine)",
    category: "supervised",
    taskType: "Klasifikasi & Regresi",
    complexity: "O(n²) hingga O(n³)",
    minData: "> 100 sampel",
    summary: "SVM mencari hyperplane terbaik yang memisahkan kelas data dengan margin maksimal. Kernel trick memungkinkan SVM menangani data non-linear dengan memproyeksikannya ke dimensi lebih tinggi.",
    analogy: "Seperti menarik garis pemisah antara dua kelompok titik dengan jarak sebesar mungkin ke kedua kelompok — bukan sekadar memisahkan, tapi mencari pemisahan terbaik.",
    icon: "separator-horizontal",
    pros: [
      "Efektif pada data berdimensi tinggi",
      "Kernel trick untuk data non-linear",
      "Margin maksimal memberikan generalisasi baik",
      "Kuat terhadap overfitting pada data high-dim",
    ],
    cons: [
      "Kurang efisien untuk dataset besar",
      "Sulit diinterpretasi (terutama kernel non-linear)",
      "Memerlukan tuning parameter (C, gamma, kernel)",
      "Tidak langsung memberikan probabilitas",
    ],
    applications: [
      "Klasifikasi teks dan sentimen",
      "Pengenalan wajah",
      "Klasifikasi jenis tanaman dari citra daun",
      "Bioinformatika (klasifikasi protein)",
    ],
  },
  {
    id: "knn",
    number: 5,
    name: "K-Nearest Neighbors (KNN)",
    nameId: "K-Nearest Neighbors (KNN)",
    category: "supervised",
    taskType: "Klasifikasi & Regresi",
    complexity: "O(n) prediksi",
    minData: "> 50 sampel (minimal)",
    summary: "KNN mengklasifikasikan data baru berdasarkan 'suara terbanyak' dari K tetangga terdekatnya dalam ruang fitur. Tidak ada proses training — semua perhitungan dilakukan saat prediksi.",
    analogy: "Seperti menentukan lingkungan tempat tinggal seseorang dari teman-teman terdekatnya — 'beri tahu aku teman-temanmu, akan kukatakan siapa dirimu'.",
    icon: "circle",
    pros: [
      "Sederhana dan intuitif",
      "Tidak perlu training (instance-based)",
      "Efektif untuk data multi-class",
      "Adaptif terhadap data baru",
    ],
    cons: [
      "Lambat untuk dataset besar",
      "Sensitif terhadap skala fitur (perlu normalisasi)",
      "Kinerja menurun pada data high-dim (curse of dimensionality)",
      "Pemilihan nilai K sangat mempengaruhi hasil",
    ],
    applications: [
      "Sistem rekomendasi (content-based filtering)",
      "Klasifikasi pola tanah berdasarkan sampel sensor",
      "Pengenalan pola tulisan tangan",
      "Deteksi anomali sederhana",
    ],
  },
  {
    id: "gradient-boosting",
    number: 6,
    name: "Gradient Boosting",
    nameId: "Gradient Boosting (XGBoost/LightGBM/CatBoost)",
    category: "supervised",
    taskType: "Klasifikasi & Regresi",
    complexity: "O(n log n)",
    minData: "> 1.000 sampel",
    summary: "Gradient Boosting membangun pohon secara berurutan — setiap pohon baru 'belajar dari kesalahan' pohon sebelumnya (residual). XGBoost, LightGBM, dan CatBoost adalah implementasi populer yang dioptimalkan.",
    analogy: "Seperti memperbaiki kesalahan secara bertahap: pertama tebak kasar, lihat kesalahannya, perbaiki, ulangi hingga kesalahan sekecil mungkin.",
    icon: "trending-up",
    pros: [
      "Akurasi state-of-the-art untuk data tabular",
      "Menangani berbagai jenis data (numerik, kategorikal)",
      "Feature importance & interpretasi",
      "Regularisasi bawaan mencegah overfit (XGBoost)",
    ],
    cons: [
      "Membutuhkan tuning hyperparameter ekstensif",
      "Lebih lambat dari Random Forest untuk dataset kecil",
      "Rentan overfit jika terlalu banyak pohon",
      "Kurang interpretabel dibanding Decision Tree",
    ],
    applications: [
      "Prediksi hasil panen berdasarkan multi-sensor IoT",
      "Rekomendasi produk e-commerce",
      "Prediksi harga saham",
      "Winning solution di banyak kompetisi Kaggle",
    ],
  },
  {
    id: "neural-network",
    number: 7,
    name: "Neural Network",
    nameId: "Neural Network (Jaringan Saraf Tiruan)",
    category: "supervised",
    taskType: "Klasifikasi, Regresi, & Lebih",
    complexity: "O(n²) per epoch",
    minData: "> 10.000 sampel (untuk deep learning)",
    summary: "Neural Network terinspirasi otak manusia: neuron buatan tersusun dalam lapisan (input, hidden, output) dengan bobot koneksi yang 'dipelajari' melalui backpropagation. MLP (Multi-Layer Perceptron) adalah bentuk paling dasar.",
    analogy: "Seperti jaringan telepon di seluruh negeri — setiap kota (neuron) terhubung dengan kota lain melalui kabel (bobot), dan sinyal (data) mengalir dari kota input ke kota output melalui sentral (hidden layer).",
    icon: "network",
    pros: [
      "Dapat mempelajari pattern yang sangat kompleks",
      "Arsitektur fleksibel (CNN, RNN, Transformer)",
      "State-of-the-art untuk gambar, teks, suara",
      "Skalabilitas dengan data & komputasi",
    ],
    cons: [
      "Membutuhkan data dalam jumlah besar",
      "Komputasi berat dan lama training",
      "Black box — sulit diinterpretasi",
      "Banyak hyperparameter yang perlu di-tuning",
    ],
    applications: [
      "Klasifikasi citra daun tanaman (CNN)",
      "Pengenalan suara & NLP",
      "Prediksi time-series sensor IoT",
      "Sistem rekomendasi modern",
    ],
  },
  {
    id: "k-means",
    number: 8,
    name: "K-Means Clustering",
    nameId: "K-Means Clustering",
    category: "unsupervised",
    taskType: "Clustering",
    complexity: "O(n · K · I)",
    minData: "> 100 sampel",
    summary: "K-Means mengelompokkan data ke dalam K cluster berdasarkan kedekatan (jarak Euclidean) ke pusat cluster. Algoritma bekerja secara iteratif: assign titik ke pusat terdekat, lalu update pusat cluster.",
    analogy: "Seperti mengatur meja pesta: letakkan K vas bunga di meja, lalu setiap tamu duduk di kursi terdekat dari vas mana pun. Setelah semua duduk, pindahkan vas ke tengah kelompok, ulangi sampai stabil.",
    icon: "circle-dot",
    pros: [
      "Sederhana dan cepat",
      "Efisien untuk dataset besar",
      "Mudah diimplementasikan",
      "Cocok untuk eksplorasi data awal",
    ],
    cons: [
      "Perlu menentukan jumlah K di awal",
      "Sensitif terhadap inisialisasi pusat awal",
      "Hanya menangkap cluster berbentuk bola",
      "Sensitif terhadap outlier",
    ],
    applications: [
      "Segmentasi zona lahan pertanian berdasarkan kesuburan tanah",
      "Segmentasi pelanggan (marketing)",
      "Kompresi gambar (color quantization)",
      "Anomali detection (data jauh dari pusat cluster)",
    ],
  },
]

export const glossaryTerms: GlossaryTerm[] = [
  { term: "Machine Learning", definition: "Cabang AI yang memungkinkan komputer belajar dari data tanpa diprogram secara eksplisit.", category: "Fundamental" },
  { term: "Supervised Learning", definition: "Pembelajaran dengan data berlabel — model belajar memetakan input ke output yang diketahui.", category: "Jenis ML" },
  { term: "Unsupervised Learning", definition: "Pembelajaran tanpa label — model menemukan pola/kelompok dalam data secara mandiri.", category: "Jenis ML" },
  { term: "Reinforcement Learning", definition: "Pembelajaran melalui trial-and-error — agent belajar dari reward dan punishment.", category: "Jenis ML" },
  { term: "Overfitting", definition: "Model terlalu 'hafal' data training sehingga performa buruk pada data baru.", category: "Evaluasi" },
  { term: "Underfitting", definition: "Model terlalu sederhana sehingga tidak mampu menangkap pola dalam data.", category: "Evaluasi" },
  { term: "Feature", definition: "Variabel input atau atribut yang digunakan model untuk membuat prediksi.", category: "Fundamental" },
  { term: "Label", definition: "Output atau target yang ingin diprediksi oleh model (pada supervised learning).", category: "Fundamental" },
  { term: "Hyperparameter", definition: "Konfigurasi yang diatur sebelum training (bukan dipelajari dari data).", category: "Fundamental" },
  { term: "Epoch", definition: "Satu kali proses model melihat seluruh data training.", category: "Neural Network" },
  { term: "Loss Function", definition: "Fungsi yang mengukur seberapa besar kesalahan prediksi model.", category: "Evaluasi" },
  { term: "Gradient Descent", definition: "Algoritma optimasi untuk meminimalkan loss dengan bergerak ke arah turunan paling curam.", category: "Optimasi" },
  { term: "Cross-Validation", definition: "Teknik evaluasi dengan membagi data menjadi beberapa lipatan dan menguji model bergantian.", category: "Evaluasi" },
  { term: "Hyperplane", definition: "Batas pemisah dalam ruang fitur dimensi tinggi — digunakan oleh SVM.", category: "Algoritma" },
  { term: "Kernel Trick", definition: "Teknik SVM untuk memproyeksikan data ke dimensi lebih tinggi tanpa komputasi eksplisit.", category: "Algoritma" },
  { term: "Decision Boundary", definition: "Garis atau permukaan yang memisahkan area keputusan kelas yang berbeda.", category: "Fundamental" },
  { term: "Confusion Matrix", definition: "Tabel yang menunjukkan performa klasifikasi: TP, FP, FN, TN.", category: "Evaluasi" },
  { term: "Precision", definition: "Dari semua yang diprediksi positif, berapa yang benar-benar positif.", category: "Evaluasi" },
  { term: "Recall", definition: "Dari semua yang benar-benar positif, berapa yang berhasil terdeteksi.", category: "Evaluasi" },
  { term: "F1-Score", definition: "Harmonic mean dari precision dan recall — keseimbangan antara keduanya.", category: "Evaluasi" },
  { term: "RMSE", definition: "Root Mean Square Error — akar dari rata-rata kuadrat error (untuk regresi).", category: "Evaluasi" },
  { term: "MAE", definition: "Mean Absolute Error — rata-rata dari nilai absolut error (untuk regresi).", category: "Evaluasi" },
  { term: "Clustering", definition: "Teknik mengelompokkan data berdasarkan kemiripan — termasuk unsupervised learning.", category: "Algoritma" },
  { term: "Dimensionality Reduction", definition: "Teknik mengurangi jumlah fitur dengan mempertahankan informasi penting.", category: "Fundamental" },
  { term: "Ensemble", definition: "Kombinasi beberapa model untuk menghasilkan prediksi yang lebih baik.", category: "Algoritma" },
  { term: "Bagging", definition: "Bootstrap Aggregating — teknik ensemble dengan melatih model pada subset data acak.", category: "Algoritma" },
  { term: "Boosting", definition: "Teknik ensemble berurutan — setiap model baru memperbaiki kesalahan model sebelumnya.", category: "Algoritma" },
  { term: "Feature Engineering", definition: "Proses membuat fitur baru dari fitur yang sudah ada untuk meningkatkan performa.", category: "Fundamental" },
  { term: "One-Hot Encoding", definition: "Mengubah data kategorikal menjadi representasi biner untuk model ML.", category: "Fundamental" },
  { term: "Normalization", definition: "Menskala fitur ke rentang tertentu (biasanya 0-1) agar setara.", category: "Fundamental" },
  { term: "Standardization", definition: "Menskala fitur agar memiliki mean=0 dan standard deviation=1.", category: "Fundamental" },
]
